'use strict';

// Extra word-problem structures: comparisons, unknown start/change, multiplicative comparison, remainders,
// area and perimeter, rates, discounts, mixed numbers and multi-step stories. Level 1 = standard, level 2 = challenge.
// Every make() computes its answer from the same numbers it prints; tests re-check ranges, signs and divisibility.
module.exports = function register(t, H) {
  const { PROFILE, int, pick, F, fmt, cents, dec } = H;

  // Typical magnitudes by grade (SC grade-level ranges are a planning guide; have an educator confirm).
  const RANGE = {
    small: { 1: [2, 6], 2: [3, 12], 3: [4, 20], 4: [6, 40], 5: [10, 80] },
    med: { 1: [5, 12], 2: [10, 40], 3: [20, 150], 4: [100, 900], 5: [500, 5000] },
    large: { 1: [10, 20], 2: [30, 99], 3: [100, 600], 4: [1000, 9000], 5: [10000, 90000] },
  };
  const Q = (r, g, k) => int(r, ...RANGE[k][g]);
  const money = (n) => `$${fmt(n)}`;
  const roundUp = (n, to) => Math.ceil((n + 1) / to) * to; // a bill that covers n with change left

  // ======================= WHOLE NUMBERS, standard =======================
  t({ id: 'w2-unknown-start', ops: ['sub'], kind: 'whole', steps: 1, level: 1, grades: [1, 5], make: (r, c, g) => { const [a, b] = PROFILE[g].addPair(r); return { text: `${c.n1} had some ${c.items}. Then ${c.n1} got ${fmt(b)} more. Now ${c.n1} has ${fmt(a + b)} ${c.items}. How many ${c.items} did ${c.n1} have at first?`, answerText: fmt(a) }; } });
  t({ id: 'w2-unknown-change', ops: ['sub'], kind: 'whole', steps: 1, level: 1, grades: [1, 5], make: (r, c, g) => { const [a, b] = PROFILE[g].subPair(r); return { text: `${c.n1} had ${fmt(a)} ${c.items}. After ${c.n1} gave some to ${c.n2}, ${fmt(a - b)} were left. How many ${c.items} did ${c.n1} give to ${c.n2}?`, answerText: fmt(b) }; } });
  t({ id: 'w2-compare-fewer', ops: ['sub'], kind: 'whole', steps: 1, level: 1, grades: [1, 5], make: (r, c, g) => { const [a, b] = PROFILE[g].subPair(r); return { text: `${c.n1} has ${fmt(a)} ${c.items}. ${c.n2} has ${fmt(b)} fewer ${c.items} than ${c.n1}. How many ${c.items} does ${c.n2} have?`, answerText: fmt(a - b) }; } });
  t({ id: 'w2-compare-howmany-more', ops: ['sub'], kind: 'whole', steps: 1, level: 1, grades: [1, 5], make: (r, c, g) => { const [a, b] = PROFILE[g].subPair(r); return { text: `${g <= 2 ? '' : `${c.setting}, `}${c.n1} has ${fmt(a)} ${c.items}. ${c.n2} has ${fmt(b)} ${c.items}. How many more ${c.items} does ${c.n1} have than ${c.n2}?`, answerText: fmt(a - b) }; } });
  t({ id: 'w2-compare-more', ops: ['add'], kind: 'whole', steps: 1, level: 1, grades: [1, 5], make: (r, c, g) => { const [a, b] = PROFILE[g].subPair(r); return { text: `${c.n1} has ${fmt(b)} ${c.items}. ${c.n2} has ${fmt(a - b)} more ${c.items} than ${c.n1}. How many ${c.items} does ${c.n2} have?`, answerText: fmt(a) }; } });
  t({ id: 'w2-three-addends', ops: ['add'], kind: 'whole', steps: 1, level: 1, grades: [1, 5], make: (r, c, g) => { const k = g === 1 ? 'small' : g === 2 ? 'small' : g === 3 ? 'med' : g === 4 ? 'med' : 'large'; const x = g === 2 ? int(r, 10, 30) : Q(r, g, k); const y = g === 2 ? int(r, 10, 30) : Q(r, g, k); const z = g === 2 ? int(r, 10, 30) : Q(r, g, k); return { text: `${g <= 2 ? '' : `${c.setting}, `}${c.n1} counted ${fmt(x)} ${c.items} in the morning. ${c.n1} counted ${fmt(y)} at lunch and ${fmt(z)} after school. How many ${c.items} did ${c.n1} count in all?`, answerText: fmt(x + y + z) }; } });
  t({ id: 'w2-seats', ops: ['mul'], kind: 'whole', steps: 1, level: 1, grades: [2, 5], make: (r, c, g) => { const [a, b] = PROFILE[g].mulPair(r); return { text: `A theater has ${fmt(a)} rows with ${fmt(b)} seats in each row. How many seats are in the theater?`, answerText: fmt(a * b) }; } });
  t({ id: 'w2-price-each', ops: ['mul'], kind: 'whole', steps: 1, level: 1, grades: [2, 5], make: (r, c, g) => { const p = g === 2 ? int(r, 2, 9) : g === 3 ? int(r, 3, 15) : g === 4 ? int(r, 8, 60) : int(r, 15, 99); const k = g === 2 ? int(r, 2, 5) : g === 3 ? int(r, 2, 9) : g === 4 ? int(r, 3, 12) : int(r, 6, 25); const [one, many] = pick(r, [['ticket', 'tickets'], ['T-shirt', 'T-shirts'], ['plant', 'plants'], ['book', 'books'], ['water bottle', 'water bottles']]); return { text: `Each ${one} costs ${money(p)}. ${c.n1} buys ${fmt(k)} ${many}. How much do the ${many} cost in all?`, answerText: money(p * k) }; } });
  t({ id: 'w2-times-as-many', ops: ['mul'], kind: 'whole', steps: 1, level: 1, grades: [3, 5], make: (r, c, g) => { const [k, a] = PROFILE[g].mulPair(r); return { text: `${c.n1} has ${fmt(a)} ${c.items}. ${c.n2} has ${fmt(k)} times as many ${c.items} as ${c.n1}. How many ${c.items} does ${c.n2} have?`, answerText: fmt(a * k) }; } });
  t({ id: 'w2-times-as-many-div', ops: ['div'], kind: 'whole', steps: 1, level: 1, grades: [3, 5], make: (r, c, g) => { const [k, a] = PROFILE[g].divPair(r); return { text: `${c.n2} has ${fmt(a * k)} ${c.items}. That is ${fmt(k)} times as many as ${c.n1} has. How many ${c.items} does ${c.n1} have?`, answerText: fmt(a) }; } });
  t({ id: 'w2-tables', ops: ['div'], kind: 'whole', steps: 1, level: 1, grades: [2, 5], make: (r, c, g) => { const [k, q] = PROFILE[g].divPair(r); return { text: `${fmt(k * q)} students are eating lunch. Each table seats ${fmt(k)} students. How many tables are needed?`, answerText: fmt(q) }; } });
  t({ id: 'w2-share-three', ops: ['div'], kind: 'whole', steps: 1, level: 1, grades: [3, 5], make: (r, c, g) => { const q = g === 3 ? int(r, 5, 40) : g === 4 ? int(r, 40, 300) : int(r, 200, 1500); return { text: `${c.setting}, ${c.n1}, ${c.n2}, and ${c.n3} share ${fmt(3 * q)} ${c.items} equally. How many ${c.items} does each person get?`, answerText: fmt(q) }; } });
  t({ id: 'w2-leftover', ops: ['div'], kind: 'whole', steps: 1, level: 1, grades: [4, 5], make: (r, c, g) => { const k = g === 4 ? int(r, 3, 9) : int(r, 6, 15); const q = g === 4 ? int(r, 12, 99) : int(r, 20, 150); const rem = int(r, 1, k - 1); return { text: `${c.n1} has ${fmt(k * q + rem)} ${c.items}. ${c.n1} puts ${k} ${c.items} in each bag. How many full bags can ${c.n1} fill? How many ${c.items} are left over?`, answerText: `${fmt(q)} full bags with ${rem} left over` }; } });
  t({ id: 'w2-area', ops: ['mul'], kind: 'whole', steps: 1, level: 1, grades: [3, 5], make: (r, c, g) => { const l = g === 3 ? int(r, 4, 12) : g === 4 ? int(r, 12, 40) : int(r, 20, 60); const w = g === 3 ? int(r, 3, 9) : g === 4 ? int(r, 8, 25) : int(r, 12, 45); const [what, unit] = pick(r, [['garden', 'feet'], ['classroom rug', 'feet'], ['playground', 'yards'], ['poster', 'inches']]); return { text: `A rectangular ${what} is ${l} ${unit} long and ${w} ${unit} wide. What is its area in square ${unit}?`, answerText: `${fmt(l * w)} square ${unit}` }; } });

  // multi-step, standard
  t({ id: 'w2-two-kinds', ops: ['mul', 'add'], kind: 'whole', steps: 3, level: 1, grades: [3, 5], make: (r, c, g) => { const p1 = g === 3 ? int(r, 2, 6) : g === 4 ? int(r, 3, 9) : int(r, 4, 15); const p2 = g === 3 ? int(r, 1, 5) : g === 4 ? int(r, 2, 8) : int(r, 2, 12); const a = int(r, 2, g === 3 ? 8 : 12); const b = int(r, 2, g === 3 ? 8 : 12); return { text: `At the bake sale, muffins cost ${money(p1)} each and cookies cost ${money(p2)} each. ${c.n1} buys ${a} muffins and ${b} cookies. How much does ${c.n1} spend in all?`, answerText: money(p1 * a + p2 * b) }; } });
  t({ id: 'w2-spend-two', ops: ['sub'], kind: 'whole', steps: 2, level: 1, grades: [2, 5], make: (r, c, g) => { const [lo, hi] = { 2: [30, 99], 3: [60, 250], 4: [150, 600], 5: [300, 1000] }[g]; const a = int(r, lo, hi); const b = int(r, Math.ceil(a * 0.15), Math.floor(a * 0.4)); const d = int(r, Math.ceil(a * 0.1), Math.floor(a * 0.3)); return { text: `${c.n1} had ${money(a)}. ${c.n1} spent ${money(b)} on lunch and ${money(d)} on a book. How much money does ${c.n1} have left?`, answerText: money(a - b - d) }; } });
  t({ id: 'w2-pages-left', ops: ['mul', 'sub'], kind: 'whole', steps: 2, level: 1, grades: [3, 5], make: (r, c, g) => { const p = g === 3 ? int(r, 8, 20) : g === 4 ? int(r, 15, 45) : int(r, 20, 60); const d = int(r, 3, 9); const extra = g === 3 ? int(r, 10, 60) : g === 4 ? int(r, 20, 150) : int(r, 40, 300); return { text: `${c.n1} reads ${p} pages of a book every day for ${d} days. The book has ${fmt(p * d + extra)} pages. How many pages are left to read?`, answerText: fmt(extra) }; } });
  t({ id: 'w2-trip-buses', ops: ['mul', 'sub'], kind: 'whole', steps: 2, level: 1, grades: [3, 5], make: (r, c, g) => { const b = g === 3 ? int(r, 2, 5) : g === 4 ? int(r, 3, 9) : int(r, 4, 12); const s = g === 3 ? int(r, 12, 36) : g === 4 ? int(r, 24, 60) : int(r, 30, 72); const x = int(r, 2, Math.floor((b * s) / 5)); return { text: `A school planned to fill ${b} buses with ${s} students on each bus. Then ${x} students stayed home. How many students went on the trip?`, answerText: fmt(b * s - x) }; } });
  t({ id: 'w2-basketball', ops: ['mul', 'add'], kind: 'whole', steps: 3, level: 1, grades: [3, 5], make: (r, c, g) => { const a = g === 3 ? int(r, 3, 9) : g === 4 ? int(r, 4, 15) : int(r, 6, 25); const b = g === 3 ? int(r, 2, 7) : g === 4 ? int(r, 3, 12) : int(r, 4, 20); return { text: `${c.n1} scored ${a} baskets worth 2 points each and ${b} baskets worth 3 points each. How many points did ${c.n1} score in all?`, answerText: fmt(2 * a + 3 * b) }; } });

  // ======================= WHOLE NUMBERS, challenge =======================
  t({ id: 'w2-c-mul-sub-div', ops: ['mul', 'sub', 'div'], kind: 'whole', steps: 3, level: 2, grades: [4, 5], make: (r, c, g) => { const b = g === 4 ? int(r, 3, 9) : int(r, 4, 12); const p = g === 4 ? int(r, 12, 48) : int(r, 24, 96); const groups = pick(r, [3, 4, 5, 6]); const total = b * p; const rem = total % groups; const lost = (rem === 0 ? groups : rem) + groups * int(r, 0, 2); return { text: `A school buys ${b} boxes of markers with ${p} markers in each box. ${lost} markers are broken. The rest are shared equally among ${groups} classes. How many markers does each class get?`, answerText: fmt((total - lost) / groups) }; } });
  t({ id: 'w2-c-buses-needed', ops: ['div'], kind: 'whole', steps: 1, level: 2, grades: [4, 5], make: (r, c, g) => { const k = g === 4 ? int(r, 24, 48) : int(r, 36, 64); const q = g === 4 ? int(r, 3, 9) : int(r, 4, 12); const rem = int(r, 1, k - 1); return { text: `A class trip has ${fmt(k * q + rem)} students. Each bus holds ${k} students. How many buses are needed so that every student has a seat?`, answerText: `${q + 1} buses` }; } });
  t({ id: 'w2-c-extra-info', ops: ['mul'], kind: 'whole', steps: 1, level: 2, grades: [3, 5], make: (r, c, g) => { const [a, b] = PROFILE[g].mulPair(r); const d = int(r, 1, Math.max(1, a * b - 1)); return { text: `${c.setting}, ${c.n1} packed ${fmt(a)} bags with ${fmt(b)} ${c.items} in each bag. ${c.n2} counted ${fmt(d)} red ${c.items} in all. How many ${c.items} did ${c.n1} pack in all?`, answerText: fmt(a * b) }; } });
  t({ id: 'w2-c-compare-products', ops: ['mul', 'sub'], kind: 'whole', steps: 3, level: 2, grades: [3, 5], make: (r, c, g) => { let [a, b] = PROFILE[g].mulPair(r); let [d, e] = PROFILE[g].mulPair(r); if (a * b === d * e) a += 1; const A = a * b; const B = d * e; const more = A > B ? c.n1 : c.n2; return { text: `${c.n1} packed ${fmt(a)} boxes with ${fmt(b)} ${c.items} in each box. ${c.n2} packed ${fmt(d)} boxes with ${fmt(e)} ${c.items} in each box. Who packed more ${c.items}, and how many more?`, answerText: `${more} packed ${fmt(Math.abs(A - B))} more` }; } });
  t({ id: 'w2-c-times-then-total', ops: ['mul', 'add'], kind: 'whole', steps: 2, level: 2, grades: [3, 5], make: (r, c, g) => { const k = int(r, 2, g === 3 ? 5 : 9); const a = g === 3 ? int(r, 4, 15) : g === 4 ? int(r, 12, 60) : int(r, 25, 150); return { text: `${c.n1} has ${a} ${c.items}. ${c.n2} has ${k} times as many ${c.items} as ${c.n1}. How many ${c.items} do they have together?`, answerText: fmt(a * (k + 1)) }; } });
  t({ id: 'w2-c-tickets-left', ops: ['div'], kind: 'whole', steps: 2, level: 2, grades: [3, 5], make: (r, c, g) => { const p = g === 3 ? int(r, 3, 9) : g === 4 ? int(r, 4, 15) : int(r, 6, 25); const q = g === 3 ? int(r, 3, 9) : g === 4 ? int(r, 4, 14) : int(r, 6, 20); const rem = int(r, 1, p - 1); return { text: `${c.n1} has ${money(p * q + rem)}. Each ticket costs ${money(p)}. How many tickets can ${c.n1} buy, and how much money will be left over?`, answerText: `${q} tickets and ${money(rem)} left over` }; } });
  t({ id: 'w2-c-laps', ops: ['mul', 'sub'], kind: 'whole', steps: 2, level: 2, grades: [3, 5], make: (r, c, g) => { const a = g === 3 ? int(r, 6, 20) : g === 4 ? int(r, 12, 60) : int(r, 25, 150); const fewer = int(r, 2, Math.floor(a * 0.8)); return { text: `${c.n1} ran ${fmt(a)} laps. ${c.n2} ran twice as many laps as ${c.n1}. ${c.n3} ran ${fewer} fewer laps than ${c.n2}. How many laps did ${c.n3} run?`, answerText: fmt(2 * a - fewer) }; } });
  t({ id: 'w2-c-stops', ops: ['add', 'sub'], kind: 'whole', steps: 3, level: 2, grades: [1, 5], make: (r, c, g) => { let a; let b; let on; let d; if (g === 1) { a = int(r, 12, 20); b = int(r, 2, 6); on = int(r, 2, 6); d = int(r, 2, Math.min(8, a - b + on - 1)); } else { a = Q(r, g, 'med'); b = int(r, 2, Math.floor(a / 3)); on = int(r, 2, Math.floor(a / 3)); d = int(r, 2, Math.floor((a - b + on) / 2)); } return { text: `A bus had ${fmt(a)} riders. At the first stop, ${fmt(b)} riders got off and ${fmt(on)} got on. At the next stop, ${fmt(d)} riders got off. How many riders are on the bus now?`, answerText: fmt(a - b + on - d) }; } });
  t({ id: 'w2-c-perimeter', ops: ['add', 'mul'], kind: 'whole', steps: 2, level: 2, grades: [3, 5], make: (r, c, g) => { const l = g === 3 ? int(r, 4, 12) : g === 4 ? int(r, 12, 40) : int(r, 20, 60); const w = g === 3 ? int(r, 3, 9) : g === 4 ? int(r, 8, 25) : int(r, 12, 45); const [what, unit, trim] = pick(r, [['garden', 'feet', 'fence'], ['bulletin board', 'inches', 'border'], ['playground', 'yards', 'rope']]); return { text: `A rectangular ${what} is ${l} ${unit} long and ${w} ${unit} wide. How many ${unit} of ${trim} are needed to go all the way around it?`, answerText: `${fmt(2 * (l + w))} ${unit}` }; } });
  t({ id: 'w2-c-packs-needed', ops: ['sub', 'div'], kind: 'whole', steps: 2, level: 2, grades: [3, 5], make: (r, c, g) => { const k = g === 3 ? int(r, 2, 6) : g === 4 ? int(r, 6, 12) : int(r, 8, 24); const p = g === 3 ? int(r, 2, 6) : g === 4 ? int(r, 3, 12) : int(r, 4, 15); const a = g === 3 ? int(r, 5, 20) : g === 4 ? int(r, 10, 60) : int(r, 20, 150); return { text: `${c.n1} needs ${fmt(a + k * p)} ${c.items} for a project and already has ${fmt(a)}. The ${c.items} are sold in packs of ${k}. How many packs does ${c.n1} need to buy?`, answerText: `${p} packs` }; } });
  t({ id: 'w2-c-change', ops: ['mul', 'add', 'sub'], kind: 'whole', steps: 3, level: 2, grades: [4, 5], make: (r, c, g) => { const a = g === 4 ? int(r, 2, 6) : int(r, 3, 9); const p = g === 4 ? int(r, 2, 6) : int(r, 3, 9); const q = g === 4 ? int(r, 3, 9) : int(r, 4, 16); const paid = roundUp(a * p + q, 10); return { text: `${c.n1} buys ${a} pens for ${money(p)} each and a notebook for ${money(q)}. ${c.n1} pays with ${money(paid)}. How much change does ${c.n1} get?`, answerText: money(paid - a * p - q) }; } });

  // ======================= DECIMALS =======================
  t({ id: 'd2-three-items', ops: ['add'], kind: 'decimal', steps: 1, level: 1, grades: [3, 5], make: (r, c) => { const a = int(r, 150, 900); const b = int(r, 60, 500); const d = int(r, 50, 700); return { text: `At the school store, ${c.n1} buys a notebook for ${cents(a)}. ${c.n1} also buys a pencil for ${cents(b)} and an eraser for ${cents(d)}. What is the total cost?`, answerText: cents(a + b + d) }; } });
  t({ id: 'd2-longer', ops: ['sub'], kind: 'decimal', steps: 1, level: 1, grades: [4, 5], make: (r, c, g) => { const places = g === 4 ? 1 : 2; const hi = 10 ** places; const a = int(r, 4 * hi, 9 * hi); const b = int(r, hi, a - hi); const what = pick(r, ['rope', 'ribbon', 'string', 'wire']); return { text: `${c.n1} has a piece of ${what} that is ${dec(a, places)} meters long. ${c.n2} has a piece that is ${dec(b, places)} meters long. How much longer is ${c.n1}'s piece?`, answerText: `${dec(a - b, places)} meters` }; } });
  t({ id: 'd2-longer-mixed-places', ops: ['sub'], kind: 'decimal', steps: 1, level: 2, grades: [5, 5], make: (r, c) => { const a = int(r, 300, 900); const bt = int(r, 10, Math.floor((a - 20) / 10)); return { text: `${c.n1} jumped ${dec(a, 2)} meters. ${c.n2} jumped ${dec(bt, 1)} meters. How much farther did ${c.n1} jump?`, answerText: `${dec(a - bt * 10, 2)} meters` }; } });
  t({ id: 'd2-walk-three', ops: ['add'], kind: 'decimal', steps: 1, level: 1, grades: [4, 5], make: (r, c) => { const a = int(r, 8, 25); const b = int(r, 8, 25); const d = int(r, 8, 25); return { text: `${c.n1} walked ${dec(a, 1)} kilometers on Monday, ${dec(b, 1)} kilometers on Tuesday, and ${dec(d, 1)} kilometers on Wednesday. How many kilometers did ${c.n1} walk in all?`, answerText: `${dec(a + b + d, 1)} kilometers` }; } });
  t({ id: 'd2-recipe', ops: ['mul'], kind: 'decimal', steps: 1, level: 1, grades: [5, 5], make: (r, c) => { const a = int(r, 12, 45); const k = int(r, 3, 9); return { text: `One batch of muffins needs ${dec(a, 1)} cups of flour. ${c.n1} bakes ${k} batches. How many cups of flour does ${c.n1} need?`, answerText: `${dec(a * k, 1)} cups` }; } });
  t({ id: 'd2-rate', ops: ['mul'], kind: 'decimal', steps: 1, level: 1, grades: [5, 5], make: (r, c) => { const a = int(r, 250, 650); const k = int(r, 3, 8); return { text: `A train travels ${dec(a, 1)} miles each hour. How far does it travel in ${k} hours?`, answerText: `${dec(a * k, 1)} miles` }; } });
  t({ id: 'd2-c-sale', ops: ['sub', 'mul'], kind: 'decimal', steps: 2, level: 2, grades: [5, 5], make: (r, c) => { const p = int(r, 1500, 4500); const off = int(r, 200, 800); const k = int(r, 2, 4); return { text: `A jacket costs ${cents(p)}. This week it is on sale for ${cents(off)} off. ${c.n1} buys ${k} jackets at the sale price. How much does ${c.n1} pay in all?`, answerText: cents((p - off) * k) }; } });
  t({ id: 'd2-c-need-more', ops: ['add', 'sub'], kind: 'decimal', steps: 2, level: 2, grades: [4, 5], make: (r, c) => { const a = int(r, 500, 1800); const b = int(r, 500, 1800); const cost = a + b + int(r, 150, 900); return { text: `${c.n1} has ${cents(a)} and ${c.n2} has ${cents(b)}. They want to buy a game that costs ${cents(cost)}. How much more money do they need?`, answerText: cents(cost - a - b) }; } });
  t({ id: 'd2-c-share-cost', ops: ['add', 'div'], kind: 'decimal', steps: 2, level: 2, grades: [4, 5], make: (r, c) => { const k = 3; const each = int(r, 150, 900); const total = each * k; const first = int(r, 300, Math.floor(total * 0.6)); return { text: `${c.n1}, ${c.n2}, and ${c.n3} are buying snacks to share. The snacks cost ${cents(first)} and ${cents(total - first)}. They split the total cost equally. How much does each person pay?`, answerText: cents(each) }; } });

  // ======================= FRACTIONS =======================
  const show = F.show;
  t({ id: 'f2-of-whole-number', ops: ['mul', 'div'], kind: 'fraction', steps: 1, level: 1, grades: [4, 5], make: (r, c, g) => { const d = pick(r, [3, 4, 5, 6, 8]); const a = int(r, 2, d - 1); const q = g === 4 ? int(r, 3, 12) : int(r, 6, 30); return { text: `${c.n1} has ${d * q} ${c.items} and gives ${a}/${d} of them to ${c.n2}. How many ${c.items} does ${c.n1} give to ${c.n2}?`, answerText: fmt(a * q) }; } });
  t({ id: 'f2-c-of-whole-left', ops: ['mul', 'sub'], kind: 'fraction', steps: 2, level: 2, grades: [4, 5], make: (r, c, g) => { const d = pick(r, [3, 4, 5, 6, 8]); const a = int(r, 2, d - 1); const q = g === 4 ? int(r, 3, 12) : int(r, 6, 30); return { text: `${c.n1} has ${d * q} ${c.items} and gives ${a}/${d} of them to ${c.n2}. How many ${c.items} does ${c.n1} have left?`, answerText: fmt(d * q - a * q) }; } });
  t({ id: 'f2-pizza-left', ops: ['sub'], kind: 'fraction', steps: 2, level: 1, grades: [4, 5], make: (r, c) => { const d = pick(r, [6, 8, 10, 12]); const a = int(r, 1, Math.floor(d / 2) - 1); const b = int(r, 1, d - a - 1); return { text: `A pizza was cut into ${d} equal slices. ${c.n1} ate ${a} slices and ${c.n2} ate ${b} slices. What fraction of the pizza is left?`, answerText: show(F.frac(d - a - b, d)) }; } });
  t({ id: 'f2-three-like', ops: ['add'], kind: 'fraction', steps: 1, level: 1, grades: [4, 5], make: (r, c) => { const d = pick(r, [5, 6, 8, 10, 12]); const a = int(r, 1, d - 1); const b = int(r, 1, d - 1); const e = int(r, 1, d - 1); return { text: `${c.n1} walked ${a}/${d} mile before school, ${b}/${d} mile at recess, and ${e}/${d} mile after school. How many miles did ${c.n1} walk in all?`, answerText: F.unit(F.frac(a + b + e, d), 'mile', 'miles') }; } });
  t({ id: 'f2-mixed-add', ops: ['add'], kind: 'fraction', steps: 1, level: 1, grades: [4, 5], make: (r, c) => { const d = pick(r, [3, 4, 5, 6, 8]); const w1 = int(r, 1, 4); const w2 = int(r, 1, 4); const a = int(r, 1, d - 1); const b = int(r, 1, d - 1); const sum = F.add(F.frac(w1 * d + a, d), F.frac(w2 * d + b, d)); return { text: `${c.n1} used ${w1} ${a}/${d} cups of flour for bread and ${w2} ${b}/${d} cups of flour for rolls. How many cups of flour did ${c.n1} use in all?`, answerText: F.unit(sum, 'cup', 'cups') }; } });
  t({ id: 'f2-mixed-sub', ops: ['sub'], kind: 'fraction', steps: 1, level: 1, grades: [4, 5], make: (r, c) => { const d = pick(r, [3, 4, 5, 6, 8]); const w1 = int(r, 3, 6); const w2 = int(r, 1, w1 - 1); const a = int(r, 1, d - 1); const b = int(r, 1, d - 1); const diff = F.sub(F.frac(w1 * d + a, d), F.frac(w2 * d + b, d)); return { text: `A board is ${w1} ${a}/${d} feet long. ${c.n1} cuts off ${w2} ${b}/${d} feet. How long is the board now?`, answerText: F.unit(diff, 'foot', 'feet') }; } });
  t({ id: 'f2-c-whole-minus-mixed', ops: ['sub'], kind: 'fraction', steps: 1, level: 2, grades: [5, 5], make: (r, c) => { const d = pick(r, [2, 3, 4, 5, 6, 8]); const w = int(r, 1, 3); const a = int(r, 1, d - 1); const total = int(r, w + 2, w + 5); return { text: `${c.n1} had ${total} pizzas for a party. The group ate ${w} ${a}/${d} pizzas. How many pizzas are left?`, answerText: F.unit(F.sub(F.frac(total), F.frac(w * d + a, d)), 'pizza', 'pizzas') }; } });
  t({ id: 'f2-c-farther', ops: ['sub'], kind: 'fraction', steps: 2, level: 2, grades: [4, 5], make: (r, c, g) => { let n1; let d1; let n2; let d2; if (g === 4) { d1 = pick(r, [4, 6, 8, 10]); d2 = d1; n1 = int(r, 3, d1 - 1); n2 = int(r, 1, n1 - 1); } else { [d1, d2] = pick(r, [[4, 8], [3, 6], [2, 4], [5, 10], [3, 4], [2, 3], [4, 6]]); do { n1 = int(r, 1, d1 - 1); n2 = int(r, 1, d2 - 1); } while (F.frac(n1, d1).n * F.frac(n2, d2).d === F.frac(n2, d2).n * F.frac(n1, d1).d); } const A = F.frac(n1, d1); const B = F.frac(n2, d2); const aFirst = A.n * B.d > B.n * A.d; const diff = aFirst ? F.sub(A, B) : F.sub(B, A); return { text: `${c.n1} ran ${n1}/${d1} mile. ${c.n2} ran ${n2}/${d2} mile. Who ran farther, and how much farther?`, answerText: `${aFirst ? c.n1 : c.n2} ran ${show(diff)} mile farther` }; } });
  t({ id: 'f2-c-pan-parts', ops: ['add', 'sub'], kind: 'fraction', steps: 3, level: 2, grades: [4, 5], make: (r, c) => { const d = pick(r, [8, 10, 12]); const a = int(r, 1, 3); const b = int(r, 1, 3); const e = int(r, 1, 3); return { text: `A pan of brownies is cut into ${d} equal pieces. ${c.n1} eats ${a} pieces. ${c.n2} eats ${b} pieces. ${c.n3} takes ${e} pieces home. What fraction of the pan is left?`, answerText: show(F.frac(d - a - b - e, d)) }; } });
  t({ id: 'f2-c-money-parts', ops: ['mul', 'sub'], kind: 'fraction', steps: 3, level: 2, grades: [5, 5], make: (r, c) => { const total = 12 * int(r, 4, 12); return { text: `${c.n1} had ${money(total)}. ${c.n1} spent 1/3 of the money on a book and 1/4 of the money on lunch. How much money does ${c.n1} have left?`, answerText: money(total - total / 3 - total / 4) }; } });
};
